name: TweetUpdate

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'develop'

      - name: dev
        run: git log --name-only $GITHUB_SHA

