name: TweetUpdate

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: dev
        run: git show --name-only $GITHUB_SHA

