name: TweetUpdate

on:
  push:
    branches:
      - master

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: './scripts/'

      - name: tweet
        run: bundle exec ruby tweet_update.rb
        working-directory: './scripts'
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  mastodon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: post to mastodon
        run: deno run --allow-env post_mastodon.ts
        working-directory: './scripts'
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
