name: TweetUpdate

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'develop'
          fetch-depth: 2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: './script/'

      - name: tweet
        run: bundle exec tweet_update.rb

